theme: jekyll-theme-minimal
title: Simulador de Probabilidad
description: Aplicación web interactiva para visualizar y simular conceptos de probabilidad
baseurl: "/SESION-7"
url: "https://orlando2019.github.io" 